apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: fetchcataas-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/jodonnell24/catops.git
        path: kubernetes/my-app-chart
        targetRevision: main
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
