---
- name: Announce Master Setup
  ansible.builtin.debug:
    msg: "Starting k3s master node installation on {{ inventory_hostname }}"

- name: Install k3s on the master node
  ansible.builtin.shell: "curl -sfL https://get.k3s.io | sh -"
  args:
    creates: /etc/systemd/system/k3s.service # Only run if the service file doesn't exist.

- name: Ensure k3s service is started
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: yes

- name: Wait for the node token to be created by k3s
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    state: present
    timeout: 60 # Wait for up to 60 seconds

- name: Get the join token from the master
  ansible.builtin.command: "cat /var/lib/rancher/k3s/server/node-token"
  register: k3s_join_token
  changed_when: false
  no_log: true

- name: Store the join token for worker nodes
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_join_token.stdout }}"
    cacheable: yes
  no_log: true

- name: Fetch the kubeconfig file from the master
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ./kubeconfig
    flat: yes

- name: Announce Master Completion
  ansible.builtin.debug:
    msg: "k3s master node setup complete."
