---
- name: Bootstrap k3s master node
  hosts: k3s_master
  become: yes
  tasks:
    - name: Install k3s server
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" sh -s - server --node-ip {{ ansible_host }}
      args:
        # This makes the task idempotent. If the file exists, the command won't run.
        creates: /etc/rancher/k3s/k3s.yaml

- name: Get the join token from the master
  hosts: k3s_master
  tasks:
    - name: Wait for k3s token to be created
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        timeout: 60
      become: yes

    - name: Read the token from the master node
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      become: yes
      register: k3s_token_b64

    - name: Store the decoded k3s token
      ansible.builtin.set_fact:
        k3s_token: "{{ k3s_token_b64['content'] | b64decode | trim }}"
      no_log: true # Don't print the secret token in logs

- name: Bootstrap k3s worker nodes
  hosts: k3s_worker
  become: yes
  tasks:
    - name: Install k3s agent on worker nodes
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io |
        K3S_URL='https://{{ hostvars[groups["k3s_master"][0]]["ansible_host"] | default(groups["k3s_master"][0]) }}:6443'
        K3S_TOKEN='{{ hostvars[groups["k3s_master"][0]]["k3s_token"] }}'
        sh -
      args:
        creates: /etc/systemd/system/k3s-agent.service
      no_log: true
