---
- name: Tear down k3s on worker nodes
  hosts: workers
  become: yes # This tells Ansible to use 'sudo' for the tasks
  tasks:
    - name: Run the k3s uninstaller script on workers
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      # We ignore errors because the script might not exist if it's already clean
      ignore_errors: yes

- name: Tear down k3s on master nodes
  hosts: masters
  become: yes
  tasks:
    - name: Run the k3s server uninstaller script on masters
      ansible.builtin.command: /usr/local/bin/k3s-server-uninstall.sh
      ignore_errors: yes
